### ISSUE TITLE
Problem : an admin was removed auto

### ISSUE THREAD

**Issue by IzuiSP** [sbpp/sourcebans-pp#252]
Hello, an admin in our SourceBans was deleted automaticaly ...
 Any idea ?

**Comment by IzuiSP** [comment]
```
///////////////////
//phperror.log//
/////////////////
[10-Mar-2017 17:53:18 Europe/London] PHP Warning:  mktime() expects parameter 4 to be integer, string given in /home/web/exolys/bans.exolys-team.fr/www/pages/page.banlist.php on line 301
[10-Mar-2017 17:53:18 Europe/London] PHP Warning:  mktime() expects parameter 4 to be integer, string given in /home/web/exolys/bans.exolys-team.fr/www/pages/page.banlist.php on line 302
[14-Mar-2017 17:50:03 Europe/London] PHP Warning:  file_get_contents(http://steamcommunity.com/openid/id/76561198213311752): failed to open stream: Connection timed out in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 447
[14-Mar-2017 17:50:03 Europe/London] PHP Fatal error:  Uncaught ErrorException: Endless redirection! in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php:679
Stack trace:
#0 /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php(911): LightOpenID->discover('http://steamcom...')
#1 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(41): LightOpenID->validate()
#2 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(72): steamOauth()
#3 {main}
  thrown in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 679
[14-Mar-2017 18:47:32 Europe/London] PHP Warning:  get_headers(http://steamcommunity.com/openid): failed to open stream: Connection timed out in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 416
[14-Mar-2017 18:48:32 Europe/London] PHP Warning:  file_get_contents(http://steamcommunity.com/openid): failed to open stream: Connection timed out in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 447
[14-Mar-2017 18:48:33 Europe/London] PHP Fatal error:  Uncaught ErrorException: No OpenID Server found at http://steamcommunity.com/openid in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php:677
Stack trace:
#0 /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php(857): LightOpenID->discover('http://steamcom...')
#1 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(34): LightOpenID->authUrl()
#2 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(72): steamOauth()
#3 {main}
  thrown in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 677
[23-Mar-2017 23:51:49 Europe/London] PHP Warning:  file_get_contents(http://steamcommunity.com/openid): failed to open stream: HTTP request failed!  in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 447
[23-Mar-2017 23:51:49 Europe/London] PHP Fatal error:  Uncaught ErrorException: Endless redirection! in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php:679
Stack trace:
#0 /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php(857): LightOpenID->discover('http://steamcom...')
#1 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(34): LightOpenID->authUrl()
#2 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(72): steamOauth()
#3 {main}
  thrown in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 679
[23-Mar-2017 23:53:09 Europe/London] PHP Fatal error:  Uncaught ErrorException: No OpenID Server found at http://steamcommunity.com/openid in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php:677
Stack trace:
#0 /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php(857): LightOpenID->discover('http://steamcom...')
#1 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(34): LightOpenID->authUrl()
#2 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(72): steamOauth()
#3 {main}
  thrown in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 677
[23-Mar-2017 23:54:10 Europe/London] PHP Warning:  get_headers(http://steamcommunity.com/openid): failed to open stream: HTTP request failed!  in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 416
[23-Mar-2017 23:54:50 Europe/London] PHP Fatal error:  Uncaught ErrorException: No OpenID Server found at http://steamcommunity.com/openid in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php:677
Stack trace:
#0 /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php(857): LightOpenID->discover('http://steamcom...')
#1 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(34): LightOpenID->authUrl()
#2 /home/web/exolys/bans.exolys-team.fr/www/steamopenid.php(72): steamOauth()
#3 {main}
  thrown in /home/web/exolys/bans.exolys-team.fr/www/includes/openid.php on line 677
[29-Mar-2017 19:20:52 Europe/Berlin] PHP Warning:  POST Content-Length of 24925569 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
```
```
//////////////
//error.log//
/////////////
[Tue Mar 07 07:49:56.897678 2017] [proxy_fcgi:error] [pid 20628] [client 91.200.12.110:50485] AH01071: Got error 'Primary script unknown\n', referer: https://bans.exolys-team.fr/wp-login.php
[Tue Mar 07 07:49:56.971544 2017] [proxy_fcgi:error] [pid 20628] [client 91.200.12.110:50485] AH01071: Got error 'Primary script unknown\n', referer: https://bans.exolys-team.fr/wp-login.php
[Sun Mar 12 16:34:21.811570 2017] [proxy_fcgi:error] [pid 29035] (70008)Partial results are valid but processing is incomplete: [client 37.146.177.137:60029] AH01075: Error dispatching request to : (reading input brigade), referer: https://bans.exolys-team.fr/index.php?p=banlist
[Sun Mar 12 16:34:21.817236 2017] [proxy_fcgi:error] [pid 29053] (70008)Partial results are valid but processing is incomplete: [client 95.84.128.235:56555] AH01075: Error dispatching request to : (reading input brigade), referer: https://bans.exolys-team.fr/index.php?p=banlist
[Fri Mar 24 00:53:09.921123 2017] [proxy_fcgi:error] [pid 15322] (32)Broken pipe: [client 136.243.103.153:59094] AH01075: Error dispatching request to : (passing brigade to output filters), referer: https://bans.exolys-team.fr/index.php?p=banlist
[Fri Mar 24 00:53:09.956329 2017] [proxy_fcgi:error] [pid 18960] (32)Broken pipe: [client 136.243.103.153:60949] AH01075: Error dispatching request to : (passing brigade to output filters), referer: https://bans.exolys-team.fr/index.php?p=banlist
[Fri Mar 24 00:54:50.630720 2017] [proxy_fcgi:error] [pid 15316] (32)Broken pipe: [client 136.243.103.153:33235] AH01075: Error dispatching request to : (passing brigade to output filters), referer: https://bans.exolys-team.fr/index.php?p=banlist
[Fri Mar 24 02:12:07.703335 2017] [proxy_fcgi:error] [pid 24610] (104)Connection reset by peer: [client 136.243.103.153:44646] AH01075: Error dispatching request to : (passing brigade to output filters), referer: https://bans.exolys-team.fr/index.php?p=banlist&page=2
[Fri Mar 24 16:58:28.849993 2017] [proxy_fcgi:error] [pid 13700] [client 117.35.207.102:47758] AH01071: Got error 'Primary script unknown\n', referer: http://bans.exolys-team.fr/wp-login.php
[Sat Mar 25 12:03:55.999342 2017] [proxy_fcgi:error] [pid 1238] (104)Connection reset by peer: [client 163.172.65.191:54576] AH01075: Error dispatching request to : (passing brigade to output filters)
[Wed Mar 29 00:32:47.654321 2017] [proxy_fcgi:error] [pid 9447] (70008)Partial results are valid but processing is incomplete: [client 88.186.246.105:55766] AH01075: Error dispatching request to : (reading input brigade), referer: https://bans.exolys-team.fr/pages/admin.uploaddemo.php
[Fri Mar 31 04:52:51.819501 2017] [proxy_fcgi:error] [pid 28496] [client 91.200.12.110:56968] AH01071: Got error 'Primary script unknown\n', referer: https://bans.exolys-team.fr/wp-login.php
[Fri Mar 31 04:52:52.051396 2017] [proxy_fcgi:error] [pid 28496] [client 91.200.12.110:56968] AH01071: Got error 'Primary script unknown\n', referer: https://bans.exolys-team.fr/wp-login.php
[Sat Apr 01 01:39:57.640230 2017] [proxy_fcgi:error] [pid 4975] [client 77.146.153.89:53844] AH01071: Got error 'Primary script unknown\n'
```
