### ISSUE TITLE
Edit Comms Details Fatal error: Uncaught Error: Cannot use object of type ADORecordSet_mysqli as array

### ISSUE THREAD

**Issue by monsterbnd** [sbpp/sourcebans-pp#606]
What are the steps to reproduce this issue?
-------------------------------------------
1. An error is observed when the comms block duration changes.

What happens?
-------------
When changing the comms block duration, a fatal php error occurs.

What were you expecting to happen?
----------------------------------
Fix php error.

Any logs, error output, etc.?
----------------------------

[25-Sep-2019 12:45:40 Europe/Moscow] PHP Fatal error:  Uncaught Error: Cannot use object of type ADORecordSet_mysqli as array in /var/www/bans.altfs.ru/public_html/pages/admin.edit.comms.php:152
Stack trace:
#0 /var/www/bans.altfs.ru/public_html/includes/page-builder.php(133): require_once()
#1 /var/www/bans.altfs.ru/public_html/index.php(37): build('Edit Block Deta...', '/admin.edit.com...')
#2 {main}
  thrown in /var/www/bans.altfs.ru/public_html/pages/admin.edit.comms.php on line 152

Any other comments?
-------------------
none

What versions of software are you using?
----------------------------------------
**Operating System:**
Distribution Name: Ubuntu
Distribution Version: 18.04.2 LTS (Bionic Beaver)
Linux Kernel: 4.15.0-58-generic
**SourceBans++ Version:**
SourceBans++ 1.7.0 | Git: 931
**PHP Version:**
php-fpm: PHP Version 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
**MySQL Version:**
mysqld Ver 5.7.27-0ubuntu0.18.04.1 for Linux on x86_64
**Link to your project:**
xxx
**Link to a phpinfo() output:**
https://drive.google.com/open?id=1x8jG9DT4y0Q82KMmKJnT4xhfPivhIbxt

**Comment by crashzk** [comment]
Fix? https://github.com/sbpp/sourcebans-pp/pull/769

**Comment by rumblefrog** [comment]
Closing — same root cause as #603, fixed by #1092 (ADOdb→PDO). If it still reproduces on `main`, please open a fresh issue with current logs. Backlog grooming pass: #1116.
