### ISSUE TITLE
Invalid SteamID input!  - /includes/SteamID/SteamID.php on line 108

### ISSUE THREAD

**Issue by Trice1984** [sbpp/sourcebans-pp#900]
Hello Team,

our problem, when we use the BAN button at the Homepage we become the error:

Fatal error: Uncaught Exception: Invalid SteamID input! in /var/www/vhosts/xloldies.de/sb.xloldies.de/includes/SteamID/SteamID.php:108 Stack trace: #0 /var/www/vhosts/xloldies.de/sb.xloldies.de/includes/SteamID/SteamID.php(84): SteamID\SteamID::resolveInputID() #1 /var/www/vhosts/xloldies.de/sb.xloldies.de/includes/SteamID/SteamID.php(56): SteamID\SteamID::to() #2 /var/www/vhosts/xloldies.de/sb.xloldies.de/pages/page.banlist.php(487): SteamID\SteamID::toSteam3() #3 /var/www/vhosts/xloldies.de/sb.xloldies.de/includes/page-builder.php(143): require_once('...') #4 /var/www/vhosts/XXXXXXX/index.php(29): build() #5 {main} thrown in /var/www/vhosts/xloldies.de/sb.xloldies.de/includes/SteamID/SteamID.php on line 108

We use the Version:
SB: 1.8.0 | Git: 1294
PHP: 8.1.19
Mysql: MariaDB

The link is: https://sb.xloldies.de/index.php?p=banlist

We hope someone can help us...

Thank u for ur help.

**Comment by Trice1984** [comment]
This error is at today again back , sorry for my bad englisch.

How can i fix it?

**Comment by Trice1984** [comment]
DELETE FROM sb_bans WHERE authid = 'BOT';   this one helps
