### ISSUE TITLE
Admin login doesnt work since update from 1.6.3 to 1.7.0!

### ISSUE THREAD

**Issue by sleip82** [sbpp/sourcebans-pp#981]
What are the steps to reproduce this issue?
-------------------------------------------
1. Updating from 1.6.3 to 1.8.0
2. Running upgrade.php

What happens?
-------------
After updating from 1.6.3 to 1.8.0 I can no longer log in, neither via steam nor via user and password. The problem is that the table sb_login_tokens does not exist in my database, can someone tell me whether this table was also missing in 1.6.3? In any case, logging in was possible in version 1.6.3.

What were you expecting to happen?
----------------------------------
That I can log in as admin

Any logs, error output, etc.?
----------------------------
FATAL ERRORUncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_409858_3.sb_login_tokens' doesn't exist
webseiten/5bo.de/bans.5bo.de/includes/Database.php Zeile 117

Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_409858_3.sb_login_tokens' doesn't exist
webseiten/5bo.de/bans.5bo.de/includes/Database.php Zeile 117
Backtrace
#0 webseiten/5bo.de/bans.5bo.de/includes/Database.php(117): PDOStatement->execute(NULL)
#1 webseiten/5bo.de/bans.5bo.de/includes/Database.php(138): Database->execute(NULL)
#2 webseiten/5bo.de/bans.5bo.de/includes/auth/Auth.php(184): Database->single()
#3 webseiten/5bo.de/bans.5bo.de/includes/auth/Auth.php(171): Auth::checkJTI('v/p4UCvpI/gJH80...')
#4 webseiten/5bo.de/bans.5bo.de/includes/auth/Auth.php(29): Auth::generateJTI()
#5 webseiten/5bo.de/bans.5bo.de/includes/auth/handler/NormalAuthHandler.php(22): Auth::login(1, 0)
#6 webseiten/5bo.de/bans.5bo.de/includes/sb-callback.php(116): NormalAuthHandler->__construct(Object(Database), 'Sleip', 'ljk2o5cgd07e', false)
#7 webseiten/5bo.de/bans.5bo.de/includes/xajax.inc.php(1090): Plogin('Sleip', 'ljk2o5cgd07e', false, '', '0')
#8 webseiten/5bo.de/bans.5bo.de/includes/xajax.inc.php(739): xajax->_callFunction('Plogin', Array)
#9 webseiten/5bo.de/bans.5bo.de/index.php(24): xajax->processRequests()
#10 {main} 

Any other comments?
-------------------
no

What versions of software are you using?
----------------------------------------
**Operating System: Linux
**SourceBans++ Version: 1.8.0
**PHP Version: 8.3.8
**MySQL Version: 
**Link to your project: https://bans.5bo.de
**Link to a phpinfo() output: https://bans.5bo.de/info.php

**Comment by rumblefrog** [comment]
Closing for stale. And the upgrade path is updater, not upgrade.php
